# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleAdmob-Swift4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleAdmob-Swift4
  pod 'Google-Mobile-Ads-SDK'
#pod 'GoogleAds-IMA-iOS-SDK', '~> 3.7'

end
